### ISSUE TITLE
iSee doesn't connect automatically after power on

### ISSUE THREAD

**Issue by mcAnswer** [sylvek/itracing2#37]
Steps to reproduce:
1. Establish a link.
2. Turn iSee off.
3. Turn iSee on.
4. iSee blinks for about two minutes and turns off.

It doesn't matter if the iTracking2 is in foreground mode or not. It even doesn't work when the app is in the real foreground and when I select my iSee from the list of devices (it shows waiting circle). Disabling and enabling a checkbox at devices' list solves the problem but is not an option in my case (I'd like to use it without pulling the phone out of my packet).

**Comment by sylvek** [comment]
huumm.. strange because I suggest with the fourth step, that your device is an MLE-15 (auto power off without bonded link) and i have the same device at home.. and i do tests with it every day.
what is your phone?

right now..
1. Turn on my isee (mle-15)
2. check the box inside itracing2
…
waiting 2min, everything is good
…
3. click on the list to display more options
4. bipping the isee => ok / signal strength => ok / all done.
5. power off my isee
…
wait 30s
…
6. power on
…
wait 2 min
…
7. everything is fine :(

i recommend to restart your phone (maybe the background service used to link the device have some troubles…)

if you could send to me some traces :-/ 
i use this command line: $ANDROID_HOME/platform-tools/adb logcat | grep itracing2

**Comment by mcAnswer** [comment]
I have SM-N9005, Android 4.4.2. Tomorrow I'll try the same test with xPrivacy disabled. Maybe it interferes somehow. Tasker detects iSee a while after power on (at the same time when iTracing2 doesn't).

**Comment by sylvek** [comment]
Any news?

**Comment by mcAnswer** [comment]
I've tried with the following test:
iSee is turned off and disabled (background link)
Enable
PowerOn
(auto pairing)
PowerOff
PowerOn
(no autopairing)
Disable
Enable
(pairing)
PowerOff
Disable
Enable
PowerOn
(no autopairing)
Disable
Enable
(pairing)
The resulting catlog is at [2016-01-19-21-40-20.txt](https://github.com/sylvek/itracing2/files/96538/2016-01-19-21-40-20.txt)
I've started  the test at 21:37:20.

**Comment by sylvek** [comment]
THKS. your log sounds good 
```
maybe this line could contains a bug: 
01-19 21:39:19.275 W/BluetoothGatt(5532): 	at net.sylvek.itracing2.BluetoothLEService$CustomBluetoothGattCallback.onCharacteristicRead(BluetoothLEService.java:222
```

But i see that you're making your test a little quickly.
i've discovered that we need to wait around 10s before to have a fonctionnal pairing, maybe, you're too impatient?

**Comment by sylvek** [comment]
i fixed some bugs from the "BluetoothLEService" .. please, if you can make tests with the version 2.0.11. Thks.

**Comment by sylvek** [comment]
Everything goes all rights?

**Comment by sylvek** [comment]
I think it's OK now
